[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"
evm_version = "cancun"
optimizer = true
optimizer_runs = 10_000

[dependencies]
"openzeppelin/openzeppelin-contracts" = "4.9.0"
"foundry-rs/forge-std" = "1.9.6"

[fmt]
line_length = 100
